#!/bin/bash
# Test curls for Amington Hall Staff Itinerary Automation
# Run individual curls or source this file

URL="https://script.google.com/macros/s/AKfycbyCW-wd4u3iYt36PZKjP9sQAqlszyVsZGX1OjyuYWRVJV7vuJfsNgPWo4KfiNOfgxrs/exec"

echo "==================================================="
echo " TEST 1: Baraat - Amington Suite, VIP + Segregation"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Khan Family",
    "Groom'\''s Name": "Ahmed Khan",
    "Bride'\''s Name": "Fatima Malik",
    "Ethnicity / Cultural Background": "Pakistani",
    "Date of the Event": "2025-09-15",
    "Event Type": "Baraat",
    "Event Timings": "6:30pm - 11pm",
    "Attendees": "Sarah (AH), James (AH)",
    "Name of First Main Point of Contact": "Tariq Khan",
    "Phone Number of First Main Point of Contact": "7891234567",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Brother",
    "Suite(s) Hired": "Amington Suite",
    "How many guests?": "150",
    "Types of tables \u2013 Applies to front tables only": "VIP",
    "Guest Arrangements": "Men & Women Segregation",
    "men-count": "80",
    "women-count": "70",
    "reserved-tables-groom": "2",
    "reserved-tables-bride": "2",
    "Have you got a table plan by chance?": "Yes",
    "Nendra Table": "on",
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "No",
    "Head Table": "Yes",
    "Cake Company Name": "Sweet Dreams Bakery",
    "Cake Contact Name": "Lisa Ahmed",
    "Number of Tiers": "3",
    "Arrangements of the cake": "To be cut up by staff and served with the tea after food.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Sweets box 1 per plate",
    "Amington Wall Screen": "Photo slideshows",
    "Foyer Screen": "Still image",
    "Additional Services": "Yes",
    "Low Fog": true,
    "Low Fog Timing": "8:00 PM",
    "Sparklers": true,
    "Sparklers Timing": "9:30 PM",
    "Catering Company Name": "Al-Aziz Catering",
    "Catering Contact Name": "Mohammed Aziz",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Catering company providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "6"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 2: Walima - Both Suites, 200 guests, Mixed"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Rahman Family",
    "Groom'\''s Name": "Bilal Rahman",
    "Bride'\''s Name": "Aisha Patel",
    "Ethnicity / Cultural Background": "Bangladeshi",
    "Date of the Event": "2025-11-22",
    "Event Type": "Walima",
    "Event Timings": "12pm - 4:30pm",
    "Attendees": "Claire (AH), Tom (AH)",
    "Name of First Main Point of Contact": "Imran Rahman",
    "Phone Number of First Main Point of Contact": "7712345678",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Father",
    "Suite(s) Hired": "Both",
    "How many guests?": "200",
    "Types of tables \u2013 Applies to front tables only": "Round",
    "Guest Arrangements": "Open Seating (Mixed)",
    "reserved-tables-groom": "3",
    "reserved-tables-bride": "3",
    "Have you got a table plan by chance?": "Yes",
    "Gift Table": true,
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "Yes",
    "Type": "DANCEFLOOR (LED style without the lights)",
    "Size": "16x16ft",
    "Head Table": "Yes",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Jordan almonds 1 per plate",
    "Amington Wall Screen": "Still image",
    "Serenity Wall Screen": "Still image",
    "Foyer Screen": "Still image",
    "Additional Services": "Yes",
    "360 Booth": true,
    "360 Booth Timing": "1:30 PM",
    "Catering Company Name": "Spice Garden Catering",
    "Catering Contact Name": "Rahim Ali",
    "Company Worked with Venue Before": "No",
    "Leftover Food & Drinks": "Catering company taking back",
    "Leftover Containers": "Catering company providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "4"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 3: Joint Day - Both Suites, Humsafar Decor"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Hussain Family",
    "Groom'\''s Name": "Zain Hussain",
    "Bride'\''s Name": "Sana Mirza",
    "Ethnicity / Cultural Background": "Pakistani",
    "Date of the Event": "2026-04-05",
    "Event Type": "Joint Day",
    "Event Timings": "All day (6 Hours)",
    "Event Timings - All day": "12pm - 6pm",
    "Attendees": "Emma (AH), Jake (AH)",
    "Name of First Main Point of Contact": "Kamran Hussain",
    "Phone Number of First Main Point of Contact": "7823456789",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Uncle",
    "Name of Second Main Point of Contact": "Nasreen Mirza",
    "Phone Number of Second Main Point of Contact": "7934567890",
    "Phone Number of Second Main Point of Contact - Prefix": "+44",
    "Relationship of Second Main Point of Contact with the Bride/Groom": "Aunt",
    "Suite(s) Hired": "Both",
    "How many guests?": "300",
    "Types of tables \u2013 Applies to front tables only": "VIP",
    "Guest Arrangements": "Men & Women Segregation",
    "men-count": "160",
    "women-count": "140",
    "reserved-tables-groom": "3",
    "reserved-tables-bride": "3",
    "Have you got a table plan by chance?": "Yes",
    "Nendra Table": "on",
    "Gift Table": true,
    "Which of the following will you be having for your event?": "Humsafar Wedding Services",
    "Dancefloor": "No",
    "Head Table": "Yes",
    "Cake Company Name": "Elegance Cakes",
    "Cake Contact Name": "Sarah Williams",
    "Cake Contact Number": "7445566778",
    "Number of Tiers": "4",
    "Arrangements of the cake": "To be boxed up and given back to the family.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Mini perfume bottles 1 per plate",
    "Amington Wall Screen": "Photo slideshows",
    "Serenity Wall Screen": "Photo slideshows",
    "Foyer Screen": "Still image",
    "Screen Details": "Wedding video to play during reception",
    "Additional Services": "Yes",
    "Low Fog": true,
    "Low Fog Timing": "2:00 PM entrance",
    "Sparklers": true,
    "Sparklers Timing": "5:00 PM sendoff",
    "Catering Company Name": "Royal Banquet Catering",
    "Catering Contact Name": "Chef Rashid",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Family bringing own containers",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "10"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 4: Wedding Reception (NON Asian) - Amington"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Johnson Family",
    "Groom'\''s Name": "Michael Johnson",
    "Bride'\''s Name": "Emily Carter",
    "Ethnicity / Cultural Background": "British",
    "Date of the Event": "2025-06-14",
    "Event Type": "Wedding Reception (NON Asian)",
    "Event Timings": "6:30pm - 11pm",
    "Attendees": "Helen (AH)",
    "Name of First Main Point of Contact": "David Johnson",
    "Phone Number of First Main Point of Contact": "7556677889",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Father",
    "Suite(s) Hired": "Amington Suite",
    "How many guests?": "120",
    "Types of tables \u2013 Applies to front tables only": "Round",
    "Guest Arrangements": "Open Seating (Mixed)",
    "reserved-tables-groom": "1",
    "reserved-tables-bride": "1",
    "Have you got a table plan by chance?": "Yes",
    "Gift Table": true,
    "Drink Station": true,
    "Which of the following will you be having for your event?": "Third Party",
    "Décor Company Name": "Floral Fantasy Ltd",
    "Contact Name": "Sophie Green",
    "Contact Number": "7667788990",
    "Dancefloor": "Yes",
    "Type": "HIP SHEET WITH CUSTOM VINYLS",
    "Size": "20x20ft",
    "Head Table": "Yes",
    "Cake Company Name": "The Cake Studio",
    "Cake Contact Name": "Claire Brown",
    "Number of Tiers": "2",
    "Arrangements of the cake": "To be cut up by staff and served with the tea after food.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Candles 1 per plate",
    "Menu Cards": "Yes",
    "Menu Cards Placement": "1 per plate",
    "Foyer Screen": "Still image",
    "DJ or Sound System": "DJ",
    "DJ Name/Company": "DJ Beats",
    "DJ Contact Number": "7778899001",
    "Additional Services": "No",
    "Catering Company Name": "Prestige Events Catering",
    "Company Worked with Venue Before": "No",
    "Leftover Food & Drinks": "Caterer taking back",
    "Leftover Containers": "Caterer providing",
    "Drinks Provider": "Third Party Company",
    "Third Party Company Name": "Premium Bar Services",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Client",
    "Hot Drinks Supplier": "Third Party Company",
    "Hot Drinks Contact Name": "Premium Bar Services",
    "VIP Parking Passes": "3"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 5: Mehndi - Serenity Suite, Dancefloor"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Iqbal Family",
    "Groom'\''s Name": "Omar Iqbal",
    "Bride'\''s Name": "Zara Sheikh",
    "Ethnicity / Cultural Background": "Pakistani",
    "Date of the Event": "2025-07-12",
    "Event Type": "Mehndi",
    "Event Timings": "6:30pm - 11pm",
    "Attendees": "Mark (AH)",
    "Name of First Main Point of Contact": "Asif Iqbal",
    "Phone Number of First Main Point of Contact": "7889900112",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Father",
    "Suite(s) Hired": "Serenity Suite",
    "How many guests?": "80",
    "Types of tables \u2013 Applies to front tables only": "Round",
    "Guest Arrangements": "Open Seating (Mixed)",
    "reserved-tables-groom": "1",
    "reserved-tables-bride": "1",
    "Have you got a table plan by chance?": "No",
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "Yes",
    "Type": "DANCEFLOOR (LED style without the lights)",
    "Size": "16x16ft",
    "Head Table": "No",
    "Favours (CCLG)": "No",
    "Serenity Wall Screen": "Photo slideshows",
    "Foyer Screen": "Still image",
    "DJ or Sound System": "In-house DJ",
    "Additional Services": "Yes",
    "Vintage Photobooth": true,
    "Vintage Photobooth Timing": "7:30 PM",
    "Catering Company Name": "Taste of Pakistan",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Family bringing own",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "2"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 6: Corporate Event - Amington Suite"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Nexus Tech Ltd",
    "Groom'\''s Name": "N/A",
    "Bride'\''s Name": "N/A",
    "Ethnicity / Cultural Background": "N/A",
    "Date of the Event": "2026-03-18",
    "Event Type": "Corporate Event",
    "Event Timings": "12pm - 4:30pm",
    "Attendees": "Lisa (AH), Rob (AH)",
    "Name of First Main Point of Contact": "Jessica Palmer",
    "Phone Number of First Main Point of Contact": "7990011223",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Event Coordinator",
    "Suite(s) Hired": "Amington Suite",
    "How many guests?": "100",
    "Types of tables \u2013 Applies to front tables only": "Round",
    "Guest Arrangements": "Open Seating (Mixed)",
    "reserved-tables-groom": "2",
    "reserved-tables-bride": "0",
    "Have you got a table plan by chance?": "Yes",
    "Which of the following will you be having for your event?": "Third Party",
    "Dancefloor": "No",
    "Head Table": "No",
    "Favours (CCLG)": "No",
    "Amington Wall Screen": "Photo slideshows",
    "Foyer Screen": "Still image",
    "Screen Details": "Company logo slideshow",
    "DJ or Sound System": "In-house sound system",
    "Additional Services": "No",
    "Catering Company Name": "Corporate Cuisine Ltd",
    "Catering Contact Name": "Paul Harris",
    "Company Worked with Venue Before": "No",
    "Leftover Food & Drinks": "Caterer taking back",
    "Leftover Containers": "Caterer providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "5"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 7: Baraat - Both Suites, Dancefloor + Cake"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Chaudhry Family",
    "Groom'\''s Name": "Hamza Chaudhry",
    "Bride'\''s Name": "Nadia Butt",
    "Ethnicity / Cultural Background": "Pakistani",
    "Date of the Event": "2026-02-28",
    "Event Type": "Baraat",
    "Event Timings": "6:30pm - 11pm",
    "Attendees": "Sam (AH)",
    "Name of First Main Point of Contact": "Usman Chaudhry",
    "Phone Number of First Main Point of Contact": "7001122334",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Brother",
    "Suite(s) Hired": "Both",
    "How many guests?": "250",
    "Types of tables \u2013 Applies to front tables only": "VIP",
    "Guest Arrangements": "Men & Women Segregation",
    "men-count": "130",
    "women-count": "120",
    "reserved-tables-groom": "2",
    "reserved-tables-bride": "2",
    "Have you got a table plan by chance?": "Yes",
    "Nendra Table": "on",
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "Yes",
    "Type": "DANCEFLOOR (LED style without the lights)",
    "Size": "20x20ft",
    "Head Table": "Yes",
    "Cake Company Name": "Bake My Dream",
    "Cake Contact Name": "Amelia Scott",
    "Cake Contact Number": "7112233445",
    "Number of Tiers": "5",
    "Arrangements of the cake": "To be cut up by staff and served with the tea after food.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Chocolates 1 per plate",
    "Amington Wall Screen": "Photo slideshows",
    "Serenity Wall Screen": "To play a video",
    "Foyer Screen": "Still image",
    "Screen Details": "Baraat video on Serenity screen",
    "DJ or Sound System": "In-house DJ",
    "Photography": "Yes",
    "Company Name": "Lens & Light Photography",
    "Additional Services": "Yes",
    "Low Fog": true,
    "Low Fog Timing": "9:00 PM entrance",
    "360 Booth": true,
    "360 Booth Timing": "7:30 PM",
    "Catering Company Name": "Mughal Kitchen",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Catering company providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "8"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 8: Walima - Serenity Suite, Elegant Moments"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Ali Family",
    "Groom'\''s Name": "Yusuf Ali",
    "Bride'\''s Name": "Maryam Hassan",
    "Ethnicity / Cultural Background": "Somali",
    "Date of the Event": "2025-08-08",
    "Event Type": "Walima",
    "Event Timings": "12pm - 4:30pm",
    "Attendees": "Priya (AH)",
    "Name of First Main Point of Contact": "Abdullahi Ali",
    "Phone Number of First Main Point of Contact": "7223344556",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Father",
    "Suite(s) Hired": "Serenity Suite",
    "How many guests?": "90",
    "Types of tables \u2013 Applies to front tables only": "Round",
    "Guest Arrangements": "Men & Women Segregation",
    "men-count": "50",
    "women-count": "40",
    "reserved-tables-groom": "1",
    "reserved-tables-bride": "1",
    "Have you got a table plan by chance?": "Yes",
    "Gift Table": true,
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "No",
    "Head Table": "Yes",
    "Cake Company Name": "Halal Sweets Bakery",
    "Cake Contact Name": "Fatima",
    "Number of Tiers": "2",
    "Arrangements of the cake": "To be boxed up and given back to the family.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Dates & chocolates 1 per plate",
    "Serenity Wall Screen": "Photo slideshows",
    "Foyer Screen": "Still image",
    "Additional Services": "No",
    "Catering Company Name": "East African Cuisine",
    "Company Worked with Venue Before": "No",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Family bringing own containers",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "3"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 9: Joint Day - Amington, 180 guests, Humsafar"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Malik Family",
    "Groom'\''s Name": "Danyal Malik",
    "Bride'\''s Name": "Hira Qureshi",
    "Ethnicity / Cultural Background": "Pakistani / Indian",
    "Date of the Event": "2026-03-21",
    "Event Type": "Joint Day",
    "Event Timings": "All day (6 Hours)",
    "Event Timings - All day": "11am - 5pm",
    "Attendees": "Chloe (AH), Ben (AH)",
    "Name of First Main Point of Contact": "Saeed Malik",
    "Phone Number of First Main Point of Contact": "7334455667",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Uncle",
    "Name of Second Main Point of Contact": "Rukhsana Qureshi",
    "Phone Number of Second Main Point of Contact": "7445566779",
    "Phone Number of Second Main Point of Contact - Prefix": "+44",
    "Relationship of Second Main Point of Contact with the Bride/Groom": "Aunt",
    "Suite(s) Hired": "Amington Suite",
    "How many guests?": "180",
    "Types of tables \u2013 Applies to front tables only": "VIP",
    "Guest Arrangements": "Open Seating (Mixed)",
    "reserved-tables-groom": "2",
    "reserved-tables-bride": "2",
    "Have you got a table plan by chance?": "Yes",
    "Nendra Table": "on",
    "Gift Table": true,
    "Which of the following will you be having for your event?": "Humsafar Wedding Services",
    "Dancefloor": "No",
    "Head Table": "Yes",
    "Cake Company Name": "Artisan Cake Co",
    "Cake Contact Name": "Rebecca Moore",
    "Number of Tiers": "3",
    "Arrangements of the cake": "To be cut up by staff and served with the tea after food.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Miniature photo frames 1 per plate",
    "Amington Wall Screen": "Still image",
    "Foyer Screen": "Still image",
    "Screen Details": "Couple photo as still image on both screens",
    "Photography": "Yes",
    "Company Name": "Golden Hour Studios",
    "Videography": "Yes",
    "Additional Services": "Yes",
    "Sparklers": true,
    "Sparklers Timing": "3:00 PM exit",
    "Pancake Cart": true,
    "Pancake Cart Timing": "1:00 PM",
    "Catering Company Name": "Zaika Catering",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Catering company providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "7"
  }'
echo -e "\n"

echo "==================================================="
echo " TEST 10: Baraat - Both Suites, All Services"
echo "==================================================="
curl -s -L -X POST "$URL" \
  -H "Content-Type: application/json" \
  -d '{
    "Name of Client": "Sheikh Family",
    "Groom'\''s Name": "Faisal Sheikh",
    "Bride'\''s Name": "Mariam Siddiqui",
    "Ethnicity / Cultural Background": "Pakistani",
    "Date of the Event": "2025-10-10",
    "Event Type": "Baraat",
    "Event Timings": "6:30pm - 11pm",
    "Attendees": "Anna (AH), Chris (AH)",
    "Name of First Main Point of Contact": "Khalid Sheikh",
    "Phone Number of First Main Point of Contact": "7556677890",
    "Phone Number of First Main Point of Contact - Prefix": "+44",
    "Relationship of First Main Point of Contact with the Bride/Groom": "Brother",
    "Name of Second Main Point of Contact": "Fauzia Siddiqui",
    "Phone Number of Second Main Point of Contact": "7667788901",
    "Phone Number of Second Main Point of Contact - Prefix": "+44",
    "Relationship of Second Main Point of Contact with the Bride/Groom": "Sister",
    "Suite(s) Hired": "Both",
    "How many guests?": "320",
    "Types of tables \u2013 Applies to front tables only": "VIP",
    "Guest Arrangements": "Men & Women Segregation",
    "men-count": "170",
    "women-count": "150",
    "reserved-tables-groom": "4",
    "reserved-tables-bride": "4",
    "Have you got a table plan by chance?": "Yes",
    "Nendra Table": "on",
    "Gift Table": true,
    "Drink Station": true,
    "Which of the following will you be having for your event?": "Elegant Moments",
    "Dancefloor": "Yes",
    "Type": "DANCEFLOOR (LED style without the lights)",
    "Size": "20x20ft",
    "Head Table": "Yes",
    "Cake Company Name": "Bliss Cake Boutique",
    "Cake Contact Name": "Nina Patel",
    "Cake Contact Number": "7778899012",
    "Number of Tiers": "6",
    "Arrangements of the cake": "To be cut up by staff and served with the tea after food.",
    "Favours (CCLG)": "Yes",
    "Favours Type": "Luxury chocolates 1 per plate",
    "Menu Cards": "Yes",
    "Menu Cards Placement": "2 per table",
    "Amington Wall Screen": "Photo slideshows",
    "Serenity Wall Screen": "To play a video",
    "Foyer Screen": "Still image",
    "Screen Details": "Baraat entrance video on Serenity, family photos on Amington",
    "DJ or Sound System": "In-house DJ",
    "Photography": "Yes",
    "Company Name": "Elite Weddings Photography",
    "Videography": "Yes",
    "Additional Services": "Yes",
    "Low Fog": true,
    "Low Fog Timing": "9:00 PM entrance",
    "Sparklers": true,
    "Sparklers Timing": "10:30 PM sendoff",
    "360 Booth": true,
    "360 Booth Timing": "7:30 PM",
    "Vintage Photobooth": true,
    "Vintage Photobooth Timing": "8:00 PM",
    "Pancake Cart": true,
    "Pancake Cart Timing": "8:30 PM",
    "Catering Company Name": "Grand Banquet Catering",
    "Catering Contact Name": "Chef Imran",
    "Company Worked with Venue Before": "Yes",
    "Leftover Food & Drinks": "Family taking home",
    "Leftover Containers": "Catering company providing",
    "Drinks Provider": "Caterer",
    "Reception Drinks": "Yes",
    "Reception Drinks Supplier": "Amington Hall",
    "Hot Drinks Supplier": "Caterer",
    "VIP Parking Passes": "12"
  }'
echo -e "\n"

echo "All 10 test curls complete."
